FROM node:current-alpine

RUN npm install -g nodemon


# Bundle APP files
WORKDIR /app

#handle package installation
COPY package*.json /app/
ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --quiet

#copy project files
COPY . .

EXPOSE 8080



